### ISSUE TITLE
Error with input file - clarifying input format

### ISSUE THREAD

**Issue by simonewebb** [phoenixding/scdiff#12]
Hello

Thanks so much for creating this very interesting tool. I am excited to trial this on my scRNA-seq expression data! I have run scdiff.py successfully using the example.E expression file you have provided. However, I am running into issues when running it on my data, which is in csv format. I run into an IndexError:list index out of range when on line 1660 of scdiff.py.

(1) - am I able to use .csv files as input for scdiff.py? (with column 1 = Cells (barcode), column 2 = Time, column 3 = Label (celltype annotation), columns 4+ = genes). I see that the filterGenes.py gives a .tsv as output for larger datasets, so I assumed input was not restricted to .E files. If it doesn't accept .csv, do you know of a way I can convert securely to .E format? Even when I have saved as .E I still get the same error.
(2) - afterthought - is this index error issue being caused by the format of my barcodes in the "Cells" column - can I use "_" here?

Thanks in advance for your help

All the best

Simone

**Comment by simonewebb** [comment]
error was due to input file not being tab delimited! thanks

**Comment by phoenixding** [comment]
Hello Simone,
I glad that you solved the problem yourself!
Yes, the input file must be tab-delimited.  Let me know if you have any
further questions.

Regards,
Jun

**Comment by simonewebb** [comment]
Hi Jun

Apologies for opening the issue prematurely! And thanks so much for your response. Things seem to be running smoothly now - very excited to see the outcome. 

I will be in touch if any issues. Have a great week

Simone

**Comment by simonewebb** [comment]
Hi Jun

After having run scdiff a few time with slight alterations, I would like to clarify how I should handle specifying root cells:

1 - My cells are heterogenous across all timepoints. In your documentation, you mention that we can use to -a 1/True flag to specify a virtual root (if we can not assume the cells at the first time point are similar). 

2 - You say that we can add a user defined root in the expression data (by, I think, naming the cell "root" in the Labels column?). 

3 - Finally, you say the root time point should be FirstTimePoint(Integer)-1. My FirstTimePoint=12.

WRT your point "**Note, don't use "-a 1" parameter if a user-defined root is added to the expression file.**", am I right in understanding that the first two points are exclusive - i.e., I should EITHER use the virtual root flag (which will create an ancester at time FirstTimePoint(Integer)-1 with average expression at FirstTimePoint) OR define a root in the expression file?

If I am correct in the case above, is it best for me (if I have root state information available) to define the root in the expression data (and can I clarify that this would be by naming the root cells "root" in the Labels column in the expression data?).

If I do this, WRT point three above, does this mean that I need to add a further line into the -k file to state that there is one cluster at FirstTimePoint(Integer)-1?, i.e., at time point 11 there is one single cluster?). Or does this mean that the cells I define as root in the expression data should have the FirstTimePoint(Integer)-1 value in their "Time" column? Or both of the above?

Finally (and seperately to the notes above), I see that you mention that time-point information is "**not informative and often misleading in some cases**", and so it is perhaps worth making all values in the expression file (Time column) equal to eachother. In this case, is it worth also running with no timepoint information (as a final run, after running with parameters you suggest?).

Thank you so much for your time, and I hope the above makes sense. Your help is greatly appreciated - the outputs for my data so far have been quite branching, which wouldn't make the most  biological sense for my trajectory. I would love to make sure I am using the correct parameters and getting the most out of this tool. 

All the best

Simone

**Comment by phoenixding** [comment]
@simonewebb 
Thank you for reporting this issue.
-------------------------------------------------------
1 - My cells are heterogenous across all timepoints. In your documentation, you mention that we can use to -a 1/True flag to specify a virtual root (if we can not assume the cells at the first time point are similar).

>>> Yes, if this is the case, you can't use the cells at the first time point as the default root cells.
There are multiple ways for you to get over this.   (1) You can use the -a 1 option, but it's not recommended as it uses the average expression in the first time point to "fake" root cells.
(2) You handpick root cells. If you have any prior knowledge, like expression of specific marker genes. Based on the expression level of those marker genes, you can choose the root cells. Please specify the time point for those selected "root" cells as the FirstTimePoint-1.  (3) In the Utils folder, I provided a python script, which can be used to guess the root cells based on Entropy.  If you have no clues about the root cells, you probably can use it to guess the root cells automatically for you.    The idea for the guess is based on gene expression entropy: root cells (e.g. multi-potent cells) tend to ha be more plastic (more varying expression and thus larger entropy) compared to those cells with fxied terms. 
------------------------------------------------------------------
2 - You say that we can add a user defined root in the expression data (by, I think, naming the cell "root" in the Labels column?).
>>> No, user defined root cells are marked by the "time", which is the second column of the expression file. The label column does not have any impact on the result, it only affects the visualization.  After you choose your root cells, please modify the "time" of those root cells to FirstTimePoint-1. 

-------------------------------------------------------------------------
3 - Finally, you say the root time point should be FirstTimePoint(Integer)-1. My FirstTimePoint=12.

WRT your point "Note, don't use "-a 1" parameter if a user-defined root is added to the expression file.", am I right in understanding that the first two points are exclusive - i.e., I should EITHER use the virtual root flag (which will create an ancester at time FirstTimePoint(Integer)-1 with average expression at FirstTimePoint) OR define a root in the expression file?

>>> Exactly.  Generally speaking, -a 1 should be the last choice as the average expression in the first time point would be a relatively bad guess of the root cell expression profile.  As  I mentioned earlier, you should specify the root cells with your prior knowledge, or you can use the script provided under the utils folder to guess the root cells based on entropy. 

--------------------------------------------------
If I am correct in the case above, is it best for me (if I have root state information available) to define the root in the expression data (and can I clarify that this would be by naming the root cells "root" in the Labels column in the expression data?).

>>> Yes, it would be great if you can specify the root cells manually, or use the provided script to guess based on entropy.   However, you can't just specify the label.  You have to change the "time" of the cells. As I mentioned, modify the time of those selected root cells to FirstTimePoint-1.  For example, if your first time is 13, you should change the time for the root cells to 12.  

-------------------------------------------------------
Finally (and seperately to the notes above), I see that you mention that time-point information is "not informative and often misleading in some cases", and so it is perhaps worth making all values in the expression file (Time column) equal to eachother. In this case, is it worth also running with no timepoint information (as a final run, after running with parameters you suggest?).
>>> Although the time point information is often misleading in some cases, but I do believe that it can still provide some information other than just expression.  I do not recommend discarding the time point totally.   However, if you believe that the time point information in your case is totally noisy and disturbing. You can try to run a pseudotime analysis tool first (e..g Slingshot https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4772-0) , and then use the pseudo time inferred as the "time point" in the expression input file. (just replace the actual time point with the pseudo time) .  

------------

Thank you so much for your time, and I hope the above makes sense. Your help is greatly appreciated - the outputs for my data so far have been quite branching, which wouldn't make the most biological sense for my trajectory. I would love to make sure I am using the correct parameters and getting the most out of this tool.

>>> I am sorry to hear that the trajectory does not make any biological sense in your case. 
But I believe it can be improved with proper adjustment of the running parameter.  The following are the steps you can try: 
(1) Try to specify the clustering config file instead using -k auto 
If you can the semiAutomaticK.py in the utils folder to visually see the cells in 2D space (by t-SNE).
Based on the visualization, you can manually specify the clustering config file.  You can refer to the readme for more details, the config file looks something like:
12    1
13    1
14    2
15    3
The first column is the time point
The second column is the # of clusters for that specific time point
(2) Try to specify root cells instead of using -a 1 
You can use the provided guessRootCells.py to choose the root cells. 
You have to provide # of clusters for the first time point. You can visually "specify"  # of clusters with the help of the t-SNE plot provided by the semiAutomaticK.py script.   For example, if you find there are 3 clusters at your first time point , say 13
Then, root cells would be 1 cluster at time point 12
time point 13 has 2 clusters left.   Your clustering config file would be :  (tab-delimted)
12    1
13    2
....
(3) If the results are still not good,  try to use the pseudo time instead of actual time, and disable the synchronization option with  -d 1 option.    
To better results, try to use a customized clustering config file.  Also, you can use the -l 1 -s 1 option to speed up. Hope it helps! Let me know if you have any further questions.

**Comment by simonewebb** [comment]
Jun, 

Your response is very thorough, clear and appreciated. Thank you for taking the time to clarify my questions. I'm excited to see the outcome

Simone
