### ISSUE TITLE
SCDIFF error on installation: Cannot import name 'Six'

### ISSUE THREAD

**Issue by paraish** [phoenixding/scdiff#13]
Hello, 
First thank you for making a helpful algorithm that is relatively easy to set up. 

I installed scdiff from github using the suggested code for Python3:
` $sudo pip3 install --upgrade https://github.com/phoenixding/scdiff/zipball/master`

There were several package dependencies that flagged errors but could be easily manually installed (and to your credit, you mentioned this in your instructions).
 
However, one error continued to flag even though the dependent package was present on my system:
`ImportError: cannot import name 'six' from 'sklearn.externals'`

I was able to bypass this by editing the code in your python files, replacing:
`from sklearn.externals import six`
to simply 
`import six`

Not sure if this will cause further issues downstream, but I thought I would bring it up here.

**Comment by phoenixding** [comment]
@paraish 
Thank you for reporting this issue.
Yes, this problem was caused by the recent upgrade of scikit-learn package (version 0.23+)
The sklearn.externals.six becomes depreciated in the sklearn 0.23 version.
I will fix the problem by specifying the sklearn versions in the setup.py file  (scikit-learn>0.20,<0.23)
