### ISSUE TITLE
running time of scdiff?

### ISSUE THREAD

**Issue by lixin4306ren** [phoenixding/scdiff#4]
Hi, my dataset has 22000 cells and I used top 10000 genes for scdiff analysis (parameters used: -s 1 -l 1). Over 12 hours, the scdiff is still running. How long does scdiff usually take for over 20000 cells? Should I downsmaple my samples to 1000 cells for each time point? Is there any way to speed up the process (eg. multiple threads)? Thanks.

**Comment by phoenixding** [comment]
@lixin4306ren 
Thanks for the comment. 
No, I would suggest not to down sample the cells.
In our method, we used all genes for analysis to reduce the information loss and thus it would need more computing resource/time for datasets with large number of cells (e.g. >20000 in your case).

However,  many strategies can be used to cut the running time. 
Instead of using all genes, you can only use genes with the largest variance in the process, which are most informative for trajectory inference.  You can get pretty similar results  (>80% cell assignment agreement ) with using top 5k-10k genes compared to all genes.  In many other single-cell studies, top 3k-5k genes are used for the analysis (e.g., https://academic.oup.com/bioinformatics/article/33/16/2504/3079150, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0927-y).
But I would recommend not to go below 3k genes if possible. 
You can do this filtering using the provided "filterGenes.py" script.  

For the 22000 cells with 5k genes, it should be able to get the results within 4-5 hours. 
Also, if you can use the -k config_\file instead of -k auto, you can also save the time for estimating K, which should make it less than 4 hours.  (estimated based on an i7@3.2G CPU)

For multiple threads functions, sorry it's currently not-supported yet.

**Comment by lixin4306ren** [comment]
Thanks for your suggestion. Finally, I got the results of this large dataset. I have one question about output visualization. How can I get plots like those in your Genome Res. paper, in which the pie charts directly showed the percentage of each cell type with cell types color bar aside (don't need mouseover on the nodes)?

**Comment by phoenixding** [comment]
@lixin4306ren 
Great.  The Genome res. paper figures are not coming from the visualization directly.
It's drawn based on the results.  You probably have to do it this way as well if you need the pie charts, at least for now.  

You can download the data for the entire model using the "download json" function, whose format is described in the readme.  With the data in json format, you would be able to draw the figures you need. 
Or, you can manually draw one using the information from the visualization.
