### ISSUE TITLE
stability of the output

### ISSUE THREAD

**Issue by lixin4306ren** [phoenixding/scdiff#5]
Hi, I used scdiff to predict lineage development model. I found the outputs quite different from the same dataset only using different top genes (5000 or 10000). If giving different k values in config files, the results also varied a lot. And these results are not consistent with my pseudotime analysis using monocle.  So which result should I use? How much can I trust these results? Thanks for your help.

Xin

result using 10000 genes
![image](https://user-images.githubusercontent.com/14223132/51875944-ededc400-23a1-11e9-8061-ed054014fe06.png)

result using 5000 genes
![image](https://user-images.githubusercontent.com/14223132/51875983-01009400-23a2-11e9-82d8-7af281fbc570.png)

**Comment by phoenixding** [comment]
@lixin4306ren 
Thanks for reporting this issue. 
The clusters in the top (10k genes) and bottom (5k genes) results are quite similar. 
The difference between the top and bottom results is the position of E3_4.0_1 (top), which is corresponding to E2_4.0_0(bottom). 

In the top result, E3_4.0_1 is in the children level of E2_4.0_0. However, in the bottom result,
E2_4.0_0 (~ E3_4.0_1 in top result) is the sibling node of the E2_4.0_1(~E2_4.0_0 in top result). 
This causes all the difference between the two tree structures. 

The reason for such difference is that we synchronize the cells/clusters in the model to make all the cells in each level within a similar differentiation stage. Such synchronization is made based on the provided gene expression (5k vs 10k).  In most cases, 5k would be enough for synchronizing the cells and will have similar results with 10k genes, but not always the same.   In your case,  5k gene seems not enough and I would recommend using 10k genes for less information loss and more appropriate cell synchronization. 

As for the pseuodtime analysis,  we are using different strategy compared with Monocle and thus it will not lead to identical cell orders. Did you also look at other pseudotime like the diffusion map as shown in the visualized model?   Also, you can look at each branch of the tree model from scdiff and see whether the cell orders in the branch are matching with the pseudotime from other methods (e.g. Monocle or Diffusion Map).   We used scdiff to study many datasets and the cell orders are quite consistent with the diffusion map. Can you check whether the cell orders in your model are indeed very different from other methods (e.g. Monocle and Diffusion map)?  If so, please let me know. I will try to figure out the reason. 

If you want to stick with the cell orders from other methods (e.g. Monocle), you can also do that by running scdiff using -d 1  parameter to disable the synchronization and use the inferred pseudotime directly.   But you would need to substitute the real capture time in the input expression dataset with pseudotime you got from other methods (e.g. Monocle). Please note, scdiff only allows discrete time, which means that you have to discrete the pseudotime to several time points. 

Please let me know if you have more questions. Thanks.

**Comment by lixin4306ren** [comment]
Thanks for your quick reply and suggestion. Different tree structures will lead to very different biological interpretation. I will try scdiff using all genes again and compare these results.

**Comment by phoenixding** [comment]
@lixin4306ren 
Yes, I agree that even slightly different tree structure will lead to very different biological interpretation. 
All input genes in the input data will be considered in the scdiff model and thus will impact the resulting model.  However, by increasing the number of genes, the resulting model will converge.  The following is an example on lung developmental data. 

(1)  resulting model with 5k genes

![screenshot from 2019-01-30 22-46-10](https://user-images.githubusercontent.com/21684886/52029562-b423d700-24e1-11e9-8de6-0ad5680d1310.png)

(2) resulting model with 10k genes
![screenshot from 2019-01-30 22-48-35](https://user-images.githubusercontent.com/21684886/52029626-036a0780-24e2-11e9-9159-cf3c62a7aeba.png)

(3) resulting model with 12k genes
![screenshot from 2019-01-30 22-49-30](https://user-images.githubusercontent.com/21684886/52029669-3a401d80-24e2-11e9-83c6-4207c72e1060.png)

(4) resulting model with all genes (15k)
![screenshot from 2019-01-30 22-49-52](https://user-images.githubusercontent.com/21684886/52029672-3ca27780-24e2-11e9-99a3-c556db5ea873.png)


Using 12k genes, we are able to get almost identical model with all genes. 
Even using 5k genes, we can get quite similar model.  

But in your case, 5k gene model and 10k gene model are quite different. 
Such difference is caused by the fact that one cell cluster was synchronized to later stage (level) in the 10k gene model compared to the 5k model as discussed in my last comment.  The information loss using 5k genes could explain the reason for such difference.  

However, if the resulting model you got with all genes are still very different to the 10k gene model, this might be suggesting that the p-value cutoff (0.05) we used to synchronize the cells/clusters are not stringent in your case.  Therefore, you might need to use more stringent cutoffs to synchronize the cells. Unfortunately, this function was not supported yet.  I'll add this option (hopefully in this week) to the method to enable customized synchronization cutoffs if needed. 

Thanks for reporting this issue and sorry for the inconvenience.

**Comment by lixin4306ren** [comment]
Here is the result using all genes (~20k), which is still different from previous results. 
It's great if users can specify more stringent cutoffs, I will wait for your update and try again. Thanks a lot and happy Chinese new year.

![image](https://user-images.githubusercontent.com/14223132/52030716-187f7e80-2554-11e9-8633-9543c8a6e198.png)

**Comment by phoenixding** [comment]
@lixin4306ren 
Thanks for the update! Happy Chinese New Year!
It's great to see that 20k model is quite similar to the 10k model you got
The only difference is the parents for the bottom left  and bottom right nodes. 
In the 20k model, they are children of E2_4.0_1 node.
However, in the 10k model, they are children of  the node (E3_4.0_0) in the next level of the same branch.  The other branches in both models are almost identical. 

I'll try to add an option for customized synchronization cutoffs in this week.  I'll keep you posted.

**Comment by phoenixding** [comment]
@lixin4306ren 
I have added a --spcut option to scdiff, with which you can customize the cutoff for synchronization.
Please refer to the readme for details.  Let me know if you have further questions.
