### ISSUE TITLE
Running example analysis results in an error: TypeError: __init__() got an unexpected keyword argument 'epsilon'

### ISSUE THREAD

**Issue by AleksZakirov** [phoenixding/scdiff#7]
Hi! Thank you very much for this piece of software. 

I am interested in trying it, however, when I try running the example: 
`python .\scdiff.py -i .\example.E -t .\example.tf_dna -k auto -o test_output`
I get the program running until it encounters an error and terminates: 

```
clustering for time: 14.0
clustering for time: 16.0
clustering for time: 18.0
building graph...
time adjustment...
connecting nodes ....
Traceback (most recent call last):
  File ".\scdiff.py", line 1712, in <module>
    main()
  File ".\scdiff.py", line 1682, in main
    viz(scg_name,G1,output)
  File "C:\Users\usr\PycharmProjects\General coding\venv\Lib\site-packages\scdiff\viz.py", line 2590, in viz
    GJ = GtoJson(G1, GL, dTD)
  File "C:\Users\usr\PycharmProjects\General coding\venv\Lib\site-packages\scdiff\viz.py", line 39, in GtoJson
    dfmap = pdm.DiffusionMap(n_evecs=2, epsilon='bgh', alpha=0.5, k=dmk)
TypeError: __init__() got an unexpected keyword argument 'epsilon'
```
Could you please suggest what might be wrong in the program itself or my setup?

Thank you!

**Comment by phoenixding** [comment]
@AleksZakirov 
After the first glimpse,  it seems that this is caused by the incompatible version of pydiffmap pacakge.
The pydiffmap was recently updated, and they removed the epsilon in the updated diffusionmap function.  You can install the older version of the pydiffmap  (<0.2.0), that should solve the problem.
I will update the code to enable the updated version of pydiffmap as soon as I can, hopefully in this week. Thank you for reporting this error.

**Comment by AleksZakirov** [comment]
@phoenixding 
Thanks for the quick response!
You are right, I just figured it out. Downgrading the pydiffmap to 0.1.1 solved the issue.

Thank you!

**Comment by phoenixding** [comment]
@AleksZakirov 
Thanks! I have fixed the code, now it should also work for pydiffmap 0.2.0
Again, thanks for reporting this error.
