### ISSUE TITLE
Getting an error in filterGenes.py: TypeError: unsupported operand type(s) for +: 'range' and 'list'

### ISSUE THREAD

**Issue by AleksZakirov** [phoenixding/scdiff#9]
Hi,
I wanted to filter my large dataset, but running the filterGenes.py results in an error:

```
File ".\filterGenes.py", line 48, in <module>
    scols=range(3)+[print(3+k) for k in range(len(stdlist)) if stdlist[k]>stdcut]
TypeError: unsupported operand type(s) for +: 'range' and 'list'
```
It seems like scols variable is supposed to contain just indices of columns (genes) that should remain in the dataset. My question is: What is the function of `range(3)` in this line? 
It seems like it's not supposed to be there...

Thank you!

**Comment by AleksZakirov** [comment]
I believe it should be `list(range(3))` to include the first 3 columns with name, time and label data.

**Comment by phoenixding** [comment]
@AleksZakirov 
Thank you for reporting this.
I tested the code in python2, in which range(3) is used to create a list [0,3].
But, the range(3) function was changed in python3 and I haven't modified the code yet.  That's why you got the reported error.  Yes, you are right, change the range(3) to list(range(3)) should solve the problem for python 3 users.  I am out of the states right now and only have limited access to internet.   I will fix the issue by this weekend or early next week.  Thanks.
